title: evilolive's Tools
tagline: A small collection of standalone tools, calculators, and references.
description: A small collection of standalone tools, calculators, and references.
theme: jekyll-theme-midnight
show_downloads: false
baseurl: ""
url: "https://evilolive420.github.io"
repository: evilolive420/evilolive420.github.io
markdown: kramdown
